vich_uploader:
    db_driver: orm

    mappings:
        floors:
            uri_prefix: /images/floors
            upload_destination: '%kernel.project_dir%/public/images/floors'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer